# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151011102433 on 2015-11-05 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20151104_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='Full_Name',
            new_name='full_name',
        ),
    ]
